export const API_ENDPOINTS = {
  LOGIN: '/login',
  REGISTER: '/register',
  LOGOUT: '/logout',
  ADDVISIT: '/prouduct/addVisit',
  FORGET_PASSWORD: '/forget-password',
  CATEGORIES: '/categorys/free',
  CATEGORIESMAIN: '/categorys',
  DIETARY: '/dietary.json',
  BRANDS: '/brands.json',
  PRODUCTS: '/prouduct',
  PRODUCTSDISCOUNT: '/prouduct/discount',
  PRODUCT: '/prouduct',
  PRODUCTSUPLLIER: '/supplier/prouducts',
  Supplier: '/supplier',
  USER: '/user',
  RELATED_PRODUCTS: '/prouduct',
  RELATED_PRODUCTS_FREE: '/prouduct/free',
  FLASH_SELL_PRODUCTS: '/products_flash_sell.json',
  BEST_SELLER_PRODUCTS: '/supplier/best',
  BEST_SELLER_GROCERY_PRODUCTS: '/supplier/best',
  POPULAR_PRODUCTS: '/products_popular.json',
  MOSTVISITED_PRODUCT: '/prouduct/mostVisited',
  CHIPS_PRODUCTS: '/prouduct/discount',
  POPCORN_JERKY_PRODUCTS: '/products_popcorn_jerky.json',
  FRESH_VEGETABLES_PRODUCTS: '/prouduct',
  SEARCH: '/prouduct/search',
  ORDERS: '/orders.json',
  ORDER: '/order.json',
  ORDER_STATUS: '/order-status.json',
  ADDRESS: '/address.json',
  PAYMENT: '/payment.json',
  CONTACT: '/contact.json',
  SHOP: '/shop.json',
  SHOPS: '/supplier',
  WISHLIST: '/wishlist.json',
};

export const CDN_BASE_URL = 'https://server.wimehr.com/';
// export const CDN_BASE_URL = 'http://localhost:3001/';
